Treat warnings/notes as error

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -14,7 +14,6 @@ jobs:
     env:
       USE_BSPM: "true"
       _R_CHECK_FORCE_SUGGESTS_: "false"
-      WARNINGS_ARE_ERRORS: "true"
       GITHUB_PAT: ${{ secrets.SURVLEARNER_TOKEN }}
     steps:
       - uses: actions/checkout@v2
@@ -39,7 +38,13 @@ jobs:
 
       - name: Test
         working-directory: r-package/survlearners
-        run: ./run.sh run_tests
+        run: |
+          ./run.sh run_tests
+          # Treat WARNING and NOTE as error
+          if ./run.sh dump_logs_by_extension "log" | grep 'WARNING\|NOTE'; then
+            echo "Found warnings/notes, treating as errors."
+            exit 1
+          fi
 
       - name: Print logs
         if: failure()
